packages:
  - "apps/*"
  - "packages/*"

confirmModulesPurge: false

overrides:
  multer: 2.2.0

supportedArchitectures:
  os:
    - linux
    - darwin
    - win32
  cpu:
    - x64
    - arm64
  libc:
    - musl
    - glibc

allowBuilds:
  "@nestjs/core": true
  "@prisma/client": true
  "@prisma/engines": true
  argon2: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
